# app/config/security.yml

security:
    encoders:
        Doplus\UserBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_SUPER_USER:  ROLE_USER
        ROLE_ADMIN:       ROLE_SUPER_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                   
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: /
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /

    access_control:
        - { path: ^/parametre/alerte , roles: ROLE_SUPER_USER }
        - { path: ^/register , roles: ROLE_SUPER_USER }
        - { path: ^/admin/delete_station , roles: ROLE_SUPER_USER }
        - { path: ^/admin/edit/station , roles: ROLE_SUPER_USER }
        - { path: ^/parametre/limitation , roles: ROLE_ADMIN }
        - { path: ^/parametre/abonnement , roles: ROLE_ADMIN }
        - { path: ^/admin/edit/user , roles: ROLE_SUPER_USER }
        - { path: ^/capteur/edit , roles: ROLE_SUPER_USER }