<?php

namespace Doplus\UserBundle\Entity;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithClientId($id) {
        $qb = $this->createQueryBuilder('u')
                    ->leftJoin('u.client', 'uc')
                    ->addSelect('uc')
                    ->where("uc.id = $id")
                    ->orderBy('u.nom')
                ;
        return $qb->getQuery()->getResult();
    }
    
    public function findUsersForAlerte($id) {
        $qb = $this->createQueryBuilder('u')
                    ->leftJoin('u.client', 'uc')
                    ->addSelect('uc')
                    ->where("uc.id = $id")
                    ->andWhere('u.etat = 1')
                    ->andWhere('u.alerte = 1')
                ;
        return $qb->getQuery()->getResult();
    }
    
    public function findUsersForPreAlerte($id) {
        $qb = $this->createQueryBuilder('u')
                    ->leftJoin('u.client', 'uc')
                    ->addSelect('uc')
                    ->where("uc.id = $id")
                    ->andWhere('u.etat = 1')
                    ->andWhere('u.alerte = 1')
                    ->andWhere('u.niveauAlerte = 2')
                ;
        return $qb->getQuery()->getResult();
    }
}
