<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * AlerteHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteHistoriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
