<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * AlerteMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
