<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * CapteurUniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapteurUniteRepository extends \Doctrine\ORM\EntityRepository
{
}
