<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * CapteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByStationId($id) {
        return $this
                ->createQueryBuilder('c')
                ->leftJoin("c.station","cs")
                ->where("cs.id = $id")
                ->getQuery()
                ->getResult()
        ;
    }
}
