<?php

namespace Doplus\ParatronicBundle\Repository;
use Doplus\ParatronicBundle\Entity\Search\ClientSearch;
/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function ClientSearch(ClientSearch $clientSearch) {
        $qb = $this->createQueryBuilder('c');
        $and = $qb->expr()->andX();
        
        if(!$clientSearch->isEmpty()) {
            if ($clientSearch->getEntite() != NULL) {
                $and->add($qb->expr()->like('c.raisonSociale', "'%".$clientSearch->getEntite()."%'"));
            }
            if ($clientSearch->getCp() != NULL) {
                $and->add($qb->expr()->like('c.cp', "'%".$clientSearch->getCp()."%'"));
            }
            if ($clientSearch->getVille() != NULL) {
                $and->add($qb->expr()->like('c.ville', "'%".$clientSearch->getVille()."%'"));
            }
        }
        else {
            return $clientSearch;
        }
        $qb->where($and);
        return $qb->getQuery()->getResult();
    }
    
    public function ClientMenu() {
        $qb = $this->createQueryBuilder('c')
                    ->orderBy('c.raisonSociale')
                ;
        return $qb->getQuery()->getResult();
    }
}
