<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * MesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithLimit($nb) {
        $qb = $this->createQueryBuilder('m')
                    ->orderBy('m.dateMesure', 'DESC')
                    ->setMaxResults($nb)
                ;
        return $qb->getQuery()->getResult();
    }
    
    public function findMesureTask($id) {
        $qb = $this->createQueryBuilder('m')
                    ->leftJoin('m.capteur', 'mc')
                    ->leftJoin('mc.station', 'ms')
                    ->leftJoin('ms.client', 'mcli')
                    ->addSelect('mc')
                    ->addSelect('ms')
                    ->addSelect('mcli')
                    ->where("m.id = $id")
                    ->andWhere('mcli.etat = 1')
                ;
        return $qb->getQuery()->getSingleResult();
    }
    
    public function findByStationId($id, $nb) {
        $qb = $this->createQueryBuilder('m')
                    ->leftJoin('m.capteur', 'mc')
                    ->leftJoin('mc.station', 'ms')
                    ->addSelect('mc')
                    ->addSelect('ms')
                    ->where("ms.id = $id")
                    ->orderBy('m.dateMesure', 'DESC')
                    ->setMaxResults($nb)
                ;
        return $qb->getQuery()->getResult();
    }
}