<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * ParametreCsvAutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreCsvAutoRepository extends \Doctrine\ORM\EntityRepository
{
}
