<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * ParametreAlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreAlerteRepository extends \Doctrine\ORM\EntityRepository
{
}
