<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * ParametreAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreAbonnementRepository extends \Doctrine\ORM\EntityRepository
{
}
