<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * ParametreLimitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreLimitationRepository extends \Doctrine\ORM\EntityRepository
{
}
