<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithClientId($id) {
        $qb = $this->createQueryBuilder('s')
                    ->leftJoin('s.client', 'sc')
                    ->addSelect('sc')
                    ->where("sc.id = $id")
                    ->orderBy('s.nom')
                ;
        return $qb->getQuery()->getResult();
    }
}
