<?php

namespace Doplus\ParatronicBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithClientId($id) {
        $qb = $this->createQueryBuilder('u')
                    ->leftJoin('u.client', 'uc')
                    ->addSelect('uc')
                    ->where("uc.id = $id")
                    ->orderBy('u.nom')
                ;
        return $qb->getQuery()->getResult();
    }
}
