services:
    doplus_paratronic.rolemanager:
        class: Doplus\ParatronicBundle\Service\DoplusRoleManager
    
    doplus_paratronic.doplus_mailer:
        class: Doplus\ParatronicBundle\Service\DoplusMailer
        arguments: ["@mailer", "@templating"]
